### ISSUE TITLE
ブランチ戦略のドキュメント化

### ISSUE THREAD

**Issue by rinkane** [kkksb/snacky#19]
どういうブランチ戦略でやっていくのか、簡単にでもドキュメントがあった方がやりやすいと思いました。
そこを決めるのは @kkksb さんだと思うので、余裕があればお願いします。

**Comment by kkksb** [comment]
@rinkane 
ありがとうございます！
時間があるときに適当に作っておきます。

**Comment by kkksb** [comment]
@rinkane 
developmentにgit-flowのドキュメントを作成しました。
![image](https://user-images.githubusercontent.com/38454723/166092676-09c22218-de52-4e4d-8ac0-1ae303dbefc5.png)

**Comment by rinkane** [comment]
派生ブランチの命名規則もあるの良いですね！
とりあえずドキュメントとしてはこれで十分だと思うので、このissueは閉じさせていただきます。
